### ISSUE TITLE
Changing Resolution loses camera on Sony Vaio Laptop

### ISSUE THREAD

**Issue by drbsoftware** [free5lot/Camera_Net#1]
Great library. One oddity, completely reproducible for me.
I have a Sony Vaio Laptop model VGN-FW373J running Windows 7 sp 1.
When I change the resolution from 1280 x 1024 to 640 x 480 the green "camera active" light goes off and then on, but the picture display is black and snapshots are also black. Sometimes it also happens when going from 1280 x 1024 to one of the other lower resolutions but not reliably. 
When the picture is black, changing to another low resolution works and so you can  get the 640 x 480 working just by changing to 320 x 240 and back.
Any ideas how to chase this one?

**Comment by free5lot** [comment]
Thanks. It seems to be a camera-specific problem. You should try two things with your camera:
1) Check the size (width and height) of snapshots. Is it really a black frame with correct (changed) resolution or not.
2) Try several other camera tools (search them on CodeProject), it could help to find out what's wrong.

I myself do not have such oddity on 4-5 cameras available, so it's up to you to check/investigate it.

**Comment by free5lot** [comment]
Outdated report.
