### ISSUE TITLE
Question: how can I crop a the camera stream at center?

### ISSUE THREAD

**Issue by FrancescoBonizzi** [free5lot/Camera_Net#19]
For example, my camera output is 640x320, but I need a smaller streaming in my window's user control, for example 300x240. I don't need to zoom it or resize it, I just need to crop to that size at center. 

Is there some useful method that I missed? I tried also to look and try to understand the method "ZoomToRect" but I had not luck.

Thanks a lot!

**Comment by free5lot** [comment]
Hi! You can ZoomToRect() to the central part and modify the size or control to the desired size.

**Comment by FrancescoBonizzi** [comment]
Thanks @free5lot!
