### ISSUE TITLE
Exposing this library as virtual camera  to use by third party application like zoom

### ISSUE THREAD

**Issue by zulfiker** [free5lot/Camera_Net#20]
Hi . first of all thank you for your  tremendous work . I was curious if it is possible to use this library as  virtual camera in a third party application like zoom ?like if i register and get in the available list of camera in zoom ? if so can you please provide instructions in brief ? thanks

**Comment by free5lot** [comment]
Hi, thanks, but this library is used to connect to cameras, not to provide any virtual camera. So, I think it's impossible.
I know there are virtual cameras in GNU/Linux (e.g. using V4L) but I don't know about Windows. Probably there are plenty of those, too.

**Comment by free5lot** [comment]
@zulfiker, I closed the issue as it's not an actual issue, but we can continue discussion here if you want.

**Comment by zulfiker** [comment]
@free5lot thanks for your reply . i was thinking if it is possible to develop a plugin like this https://github.com/CatxFish/obs-virtual-cam which work with popular obs studio application . let me know your thoughts . if it is possible then may be i can start working on that . benefit would be everything would be c# and there would not be any need of c++ . right now so far whatever i found all virtual camera is written in c++

**Comment by free5lot** [comment]
@zulfiker I understand your idea, but my library is useless for this purpose, it will work with virtual camera but not as virtual camera.
You can lookup DirectShowLib library for wrappers over native C++ code, maybe something similar can be used to wrapper existing virtual cameras solutions. But I think my library cannot help with it at all.
