### ISSUE TITLE
Getting no combination of intermediate filters could be found

### ISSUE THREAD

**Issue by kernello** [free5lot/Camera_Net#21]
Getting **no combination of intermediate filters could be found** whenever trying to call **GraphBuilding_ConnectPins**(). My working machine is a fresh windows 10. I used Camera.cs as given this repo. But the same code working fine in the development machine. What should I do here?.

Thanks,

**Comment by free5lot** [comment]
Just recently I had one similar report for the hardware that should work and worked for ages with Camera_Net. It was also on just-installed clean Win10 (not even up to date). 
I'm not sure what's the reason and don't have this situation now. I think it's somehow connected with the system or DirectX, maybe Windows updates should fix it?

If you have any additional information or solution - feel free to post it here.

**Comment by free5lot** [comment]
@kernello have you solved it in your case?

**Comment by spaul73** [comment]
@kernello @free5lot getting the same issue on a bunch of Panasonic tablets that were reimaged. Everything was working fine before reimaging. I don't have the tablets myself so debugging is very difficult. Any ideas or advice as to what should be installed after reimaging for it to work or any specific prerequisites without which this error seems to propping up?

**Comment by free5lot** [comment]
> Any ideas or advice as to what should be installed after reimaging for it to work or any specific prerequisites without which this error seems to propping up?

Sorry, no ideas. Feel free to post solution or any additional information here if you solve it.

**Comment by spaul73** [comment]
This specific issue was indeed related to camera drivers. A driver reset fixed it.

Another peculiar bug we discovered was that the camera preview would not show up when logging in to the tablets through RDP, we just got a black screen for preview but pictures were being clicked. When accessing physically, the preview worked fine.

**Comment by free5lot** [comment]
OK, the issue was in the driver and not the Library.

About RDP - it's probably because preview is shown using DirectX using videocard directly, and I'm not sure if it can work properly with RDP (when video output is not connected to video-card directly).
