### ISSUE TITLE
Will this work on Uno Platform?

### ISSUE THREAD

**Issue by StoutOne** [free5lot/Camera_Net#22]
Hi. Can this work on Uno Platform, specifically the UWP and Linux platforms? Or is it only for the WPF platform?

Thanks.

**Comment by free5lot** [comment]
It's a wrapper around DirectX. So, it's not about UWP/WPF/Winforms, it's about DirectX that is not ported to GNU/Linux. 
So, it won't work for you.

**Comment by StoutOne** [comment]
Thank you.
