### ISSUE TITLE
Will this work on Uno Platform?

### ISSUE THREAD

**Issue by StoutOne** [free5lot/Camera_Net#23]
Hi. Can this work on Uno Platform, specifically the Linux platform? Or is it only for the WPF platform?

Thanks.

**Comment by free5lot** [comment]
Hi. Short answer - probably no. Longer answer was made in #22.

**Comment by StoutOne** [comment]
Oops, sorry for reposting the question - I couldn't find the link, so I thought it was somehow lost. Thank you for the answer.
