### ISSUE TITLE
How to add event/callback mechanism for new camera frames

### ISSUE THREAD

**Issue by Asad02021999** [free5lot/Camera_Net#25]
Hi i would like to add or use event oriented mechanism to get new camera frames, currently i can get the new frame by calling `SnapshotSourceImage()` available in the camera or camera control class but this requires polling technique e.g. a timer or separate thread to keep polling new frames is there any way to subscribe to an event and get the latest image/bitmap from there?

**Comment by free5lot** [comment]
You can modify SampleGrabber callback code to call events every frame. Take into account that it can be slow and CPU-consuming for large frames and high frame rate. In that case, you may want to process only some frames (like once a second or something).

**Comment by free5lot** [comment]
Closing it as it's not an issue but question.
