### ISSUE TITLE
1080p Video Capture

### ISSUE THREAD

**Issue by irfansagir** [free5lot/Camera_Net#4]
Hi,
I have logitech c922 webcam. When i select  1920x1080 resolution. The video is previewing slowly. How can I solve this problem?

**Comment by free5lot** [comment]
Hi. Try to run it in some general software, like GraphStudioNext 
https://github.com/cplussharp/graph-studio-next
Make a simple graph, set 1080p resolution and run it. Does it work in this resolution smoothly? If not - the problem is probably with drivers or some camera-specific thing.
