### ISSUE TITLE
Windows service error

### ISSUE THREAD

**Issue by nosuch** [free5lot/Camera_Net#8]
While using the library to stream images to a website. I get the following error on the AddFilter_Renderer function.

Creating an instance of the COM component with CLSID {51B4ABF3-748F-4E3B-A276-C828330E926A} from the IClassFactory failed due to the following error: 80040273 Exception from HRESULT: 0x80040273.

But when I debug the service direclty through VS, there is no error. Could this be caused by user rights? I'm a bit stumped and dont know how to proceed.

Any help would be greatly appreciated.
Thanks

**Comment by free5lot** [comment]
Have you tried GraphStudioNext to make and run the graph manually? Does it work?

**Comment by free5lot** [comment]
And about error, from the DirectX documentation:
> VFW_E_DDRAW_CAPS_NOT_SUITABLE
> 0x80040273
> Either DirectDraw has not been installed or the video card capabilities are not suitable. Make sure the display is not in 16-color mode.

So, I'm not sure why it works for you in debug and not in release. If you meant admin rights, then it's probably not it.
