### ISSUE TITLE
thanks,window minimize raisError,what about using framework 3.5?

### ISSUE THREAD

**Issue by gselec** [free5lot/Camera_Net#9]
hello!thanks this project!i use it in my program.
and 2 suggests:
1:when window minimize rais-Error,UpdateOutputVideoSize.
2:what about using framework 3.5?i change it to 3.5,vs2015 compile success.

**Comment by free5lot** [comment]
Hi, thanks.
1) Probably some kind of COM error on window minimizing. What OS are you using?
2) You can compile the code for .Net 3.5 and it should work. On the other hand 3.5 is obsolete - it's huge in size and fully replaceable with smaller newer versions (4 and further), so if you need 3.5 you can use it, but I would recommend to migrate to .Net 4.

**Comment by gselec** [comment]
1:my OS is windows 7, vs2015.
2:thanks.

**Comment by free5lot** [comment]
The library is compatible with .NET 2 - 4+.
